### ISSUE TITLE
Why is the bias of wn_fc2 of class WeightNet in weightnet.py set to be false?

### ISSUE THREAD

**Issue by ZhouYuxuanYX** [megvii-model/WeightNet#1]
Hi,

I am trying to apply WeightNet to my own project and have a question about the second grouped fully connected layer of WeightNet: why is the bias set to false? Is there any reason behind this?

**Comment by nmaac** [comment]
Hi @ZhouYuxuanYX , we achieve comparable accuracy with or without the bias term. 
We removed the term for better optimizing the speed of that layer. For example, we can use [batched_matrix_mul (W,X)](https://megengine.org.cn/doc/latest/api_zh/megengine.functional.html?highlight=batched%20mat%20mul#megengine.functional.nn.batched_matrix_mul) to achieve better speed for the special point-wise conv1x1, with W(-1, oup, inp) and X(-1, inp, H*W).

**Comment by ZhouYuxuanYX** [comment]
Thanks a lot!

**Comment by ZhouYuxuanYX** [comment]
> Hi @ZhouYuxuanYX , we achieve comparable accuracy with or without the bias term.
> We removed the term for better optimizing the speed of that layer. For example, we can use [batched_matrix_mul (W,X)](https://megengine.org.cn/doc/latest/api_zh/megengine.functional.html?highlight=batched%20mat%20mul#megengine.functional.nn.batched_matrix_mul) to achieve better speed for the special point-wise conv1x1, with W(-1, oup, inp) and X(-1, inp, H*W).

Thanks a lot!
