### ISSUE TITLE
Should the standard pointwise convolution in the skip path of Resblock (upsample/downsample=True) be kept or also replaced by WeightNet?

### ISSUE THREAD

**Issue by ZhouYuxuanYX** [megvii-model/WeightNet#2]
Hi,

I have a question about applying WeightNet to residual blocks with upsampling/downsampling.  In this case, the skip path also has a 1x1 convolution. Should this conv layer also be replaced by WeightNet? Or it is better to keep it as standard convolution?

**Comment by nmaac** [comment]
Hi @ZhouYuxuanYX , for deep CNNs you do not have to replace all the convolutions , replacing 1 convolution in each block already shows improvements.

**Comment by ZhouYuxuanYX** [comment]
> Hi @ZhouYuxuanYX , for deep CNNs you do not have to replace all the convolutions , replacing 1 convolution in each block already shows improvements.

Thank you very much for the hint:)
