### ISSUE TITLE
error with distributed training

### ISSUE THREAD

**Issue by jmkim0309** [megvii-model/WeightNet#6]
Hi, 
Thank you for this great work and code!
When I tried to run the code with multi-gpus, I got an error in the following line. 
https://github.com/megvii-model/WeightNet/blob/ea318d8c6d51a5f12fffbcc2ca17a1e6feef1a1d/train.py#L156
 
And the error log is as follows: 
 
  loss = dist.all_reduce_sum(loss, "train_loss") / dist.get_world_size()
  File "/opt/conda/lib/python3.7/site-packages/megengine/distributed/functional.py", line 238, in all_reduce_sum
    assert _group_check(key, nr_ranks), "key, nr_ranks should be set at the same time"
AssertionError: key, nr_ranks should be set at the same time

I'm new to using MegEngine and could not find any related issues by googling. 
Please let me know how to resolve this error. 
Thank you!

**Comment by zhouyizhuang-megvii** [comment]
This is a known issue since we've changed the API of distributed operators. In newer versions of megengine, i.e. > 0.5.0, just call

`loss = dist.all_reduce_sum(loss) / dist.get_world_size() ` without the `"train_loss"` argument

**Comment by jmkim0309** [comment]
Now it works! thank you 👍
