### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by czy112** [megvii-model/WeightNet#7]
When I convert it to the Pytorch version, I have the following problems. Can you help me solve them？thanks
error:    
   x_gap = x.mean(axis=2,keepdims=True).mean(axis=3,keepdims=True)
TypeError: mean() received an invalid combination of arguments - got (axis=int, keepdims=bool, ), but expected one of:
 * ()
 * (torch.dtype dtype)
 * (tuple of ints dim, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: axis, keepdims
 * (tuple of ints dim, bool keepdim, torch.dtype dtype)
 * (tuple of ints dim, bool keepdim)
      didn't match because some of the keywords were incorrect: axis, keepdims

**Comment by nmaac** [comment]
Please refer to [torch API](https://pytorch.org/docs/stable/generated/torch.mean.html) which uses the parameters `dim` and `keepdim`.

**Comment by czy112** [comment]
> Please refer to [torch API](https://pytorch.org/docs/stable/generated/torch.mean.html) which uses the parameters `dim` and `keepdim`.

I have tried many times and found no success. Do you know how to convert？thanks
x_gap = x.mean(axis=2,keepdims=True).mean(axis=3,keepdims=True)

**Comment by nmaac** [comment]
* As the error info mentioned:  the combination of arguments `(axis, keepdims)` is not valid, the keywords were incorrect;
* As the error info suggested: you should use `(dim, keepdim)` instead, because of the difference between MegEngine API and torch API.

**Comment by DequanWang** [comment]
@nmaac @megvii-model Please check my [unofficial PyTorch implementation](https://github.com/DequanWang/weightnet.pytorch).
