### ISSUE TITLE
5-D tensors as weight for Conv2d?

### ISSUE THREAD

**Issue by ruiyuanlu** [megvii-model/WeightNet#8]
Thanks for this outstanding work, I'm wondering why the weightnet.py use 5D tensors as weights for F.conv2d?
Does this really work for F.conv2d?

Actually this will raise errors for PyTorch, so is there a different behavior using MegEngine?
e.g. the code [here](https://github.com/megvii-model/WeightNet/blob/669b5f4c0c46fd30cd0fedf5e5a63161e9e94bcc/weightnet.py#L42).

Looking forward to your reply.

**Comment by nmaac** [comment]
MegEngine uses a [5D tensor](https://megengine.org.cn/doc/latest/api_zh/megengine.module.html?highlight=conv2d#megengine.module.conv.Conv2d) as the grouped convolutional kernel, which is different from PyTorch API.
